### PR TITLE
added installSpotbit script, help & config - tested and working

### PR DESCRIPTION
**Pull request by jodobear**
check `installSpotbit_help.sh` for details on the script.

### CODE REVIEW

**Comment by jodobear** [comment]
added systemd service for spotbit in `installSpotbit.sh`

**Comment by jodobear** [comment]
1. In `server.py` (line 17) the `spotbit.log` path needs to be a full path to look set logs in the spotbit folder not the directory from where the service is run.
2. Updated python3.8 path in `spotbit.service`

**Comment by ChristopherA** [comment]
There are conflicts in server.py, possibly because #20 was merged last night.

Please let @watersnake1 know when you want his review on this PR as lead. He can merge to master anything that that he didn't write (otherwise right now it is me.) I know that there may be a coindesk article pointing to this page this week.

**Comment by jodobear** [comment]
1. All conflicts fixed.
2. Set `spotbit.log` directory to `~spotbit/.spotbit` as it's a local file not a repo file and won't interfere with repo updates.
3. Extra whitespace cleaned.

`installSpotbit.sh` has been tested by @watersnake1 and is ready to merge.

**Review by ChristopherA — APPROVED** [review]
As there have been two confirmations of this PR, I am merging to master.

**Comment by jodobear** [comment]
the commits are now verified

**Pull request merged**
