### PR TITLE
Refactoring Spotbit

### LINKED ISSUE #54: SpotBit should provide human-friendly names for exchanges.
SpotBit provides server names that are all lower case:

```json
[
	"gemini",
	"bitstamp",
	"okcoin",
	"coinbasepro",
	"kraken",
	"bitfinex",
	"bitflyer",
	"liquid",
	"coincheck",
	"bitbank",
	"zaif",
	"hitbtc",
	"binance",
	"okex",
	"gateio",
	"bitmax"
]
```

These all lower-case names are fine as internal identifiers of exchanges for use in the API, but are not true to the brands of these exchanges. It would be more helpful if SpotBit provided user-facing information about each exchange; at least the user-facing name, web site URL, and ISS country code for the exchange headquarters.

```json
[
  {"id": "kraken", "name": "Kraken", "url": "https://www.kraken.com/", "country": "US"},
  {"id": "ascendex", "name": "AscendEX", "url": "https://ascendex.com/", "country": "SG"}
]
```

These records could also carry information about which currencies SpotBit is configured to get information on from each exchange:

```json
[
  {"id": "kraken", "name": "Kraken", "url": "https://www.kraken.com/", "country": "US", "currencies": ["USD"]},
  {"id": "ascendex", "name": "AscendEX", "url": "https://ascendex.com/", "country": "SG", "currencies": ["USD", "JPY", "GBP"]}
]
```

### PR DESCRIPTION
**Pull request by nochiel**
- [x] Improve handling of exchanges.
- [x] Improve readability of average price calculation.
- [x] Remove database functionality.
- [x] Improve retrieval of paginated historical data so that redundant data is not returned.
    - [x] Test: #52.
        - [x] Make sure duplicate data isn't returned to the client.
        - [x] Ensure pagination works as expected.
- [x] Add `/exchanges` endpoint that returns exchange metadata. Fixes #54.
    - [x] Return exchange metadata when a client requests a price.
- [x] Cleanup variable and function naming style. (https://google.github.io/styleguide/pyguide.html#316-naming)
- [x] Cleanup API to improve ergonomics. (Ref. #51)
    - [x] Document API.
- [x] Migrate from Flask to FastAPI for:
    - Automatic generation of API documentation.
        - API documentation is now found at `http://localhost:5000/docs`
    - Easy type and validation of APIs.
- [x] Improve error handling for API calls. Clients should receive good errors and HTTP responses.
- [x] Improve logging so that if Spotbit crashes, we know exactly why.

## To be done in separate PRs.

- [ ] Tests
    - [ ] Tests for APIs.
    - [ ] Tests for the database to makes sure data is stored correctly.
- [ ] Migration
    - [ ] Update README with breaking changes.
    - [ ] Migration script. (Do we need it?)
    - [ ] Migrate web app to new API.
- [ ] Improve installation process?

### CODE REVIEW

**Comment by nochiel** [comment]
@icculp Please could you review this PR?

**Comment by nochiel** [comment]
This is closed by #58 which was based on this branch.

**Comment by k9ert** [comment]
What was the rationale for removing the database? Now, spotbit does not have any kind of caching-functionality, does it?

**Comment by nochiel** [comment]
> What was the rationale for removing the database? Now, spotbit does not have any kind of caching-functionality, does it?

- The database was essentially just copying/downloading exchange databases. Given that price data is really only relevant in a situation where transacting/accounting is necessary, it's reasonable to assume that the user will configure Spotbit to use exchanges they prefer and that are available at any given time. 
- The caching was not adding a significant performance benefit given how fast most exchange APIs already are.  (The main speed bottleneck when using Spotbit over Tor seems to be Tor itself, not exchanges.)
- The database related code paths were additional unnecessary complexity. (Though, It is good that caching was attempted initially to see if it was worthwhile.)

**Comment by ChristopherA** [comment]
I know that I'd like to see a database as an option, even if it isn't used for caching, as historical information may not always be available in the future. But this is a separate use case than the current price, and tying them together (both a cache and a historical database) in a single system caused problems. A new architecture is needed that separates them.

**Comment by ChristopherA** [comment]
Is there a new issue on this topic? Is should be be linked here, as this issue is closed.

**Comment by k9ert** [comment]
I can't follow the rationale to be honest. Price data could be usefull in so much more scenarios than just transacting/accounting and having historical data around might also be very useful. E.g. for [specter-desktop](https://github.com/cryptoadvance/specter-desktop) there is [warden](https://github.com/pxsocs/warden) which we currently transform into a specter-extension. This one definitely likes to have historical price-data available.

Also one of the Summer-of-bitcoin-projects is to make spotbit a specter-plugin and as the DB is removed, the project effectively forked this project.

**Comment by k9ert** [comment]
> That could of course be added as a feature to SpotBit but it's already trivial for an app to do that for itself, no?

This is imho exactly the stuff which an app don't want to deal with. In your project description, you write:

> It can either be used as a repository of historical data that allows for more frequent API requests, or as a simple wrapper around exchange APIs that premits the user to collect information over Tor.

This is imho the point: As an app i don't want to care how that data is obtained. I just want to use it and it's happy that some other app (spotbit) is taking care of the nitty-gritty details of that. Making it just available without caching it somehow doesn't add much value and it's also not very efficient for the operator, operating spotbit for a number of users (e.g. a raspiblitz owner being the uncle jim of his family OR a publicly available spotbit instance operated by someone who wants to give back to the community). This might even result in blacklisting the instance because it creates too many useless requests.

**Comment by nochiel** [comment]
@k9ert I think I'm beginning to understand the feature and use case you have in mind. Please have a look at #66. Do feel free to add any feature requests that you feel could improve that issue or make it better suited to your needs?

**Pull request closed without merging**
