### PR TITLE
PR for Alpha Version 3

### PR DESCRIPTION
**Pull request by watersnake1**
This is the pull request for releasing spotbit alpha version 3. 
In addition to improvements in stability and bug fixes, there are the following changes:

* Better html landing page at '/'
* Methods for finding and filling gaps in historical data
* A fully updated README that is more comprehensive
* An improved install script that automatically installs and configures python3.8 and tor, moves spotbit's source code to the spotbit user's source folder, and creates a systemd service for spotbit
* Curated lists: for USD, GBP, EUR, JPY and USDT, there is a list of 5 popular exchanges, selected based on daily volume, coinmarketcap's confidence rating, and support for ccxt, that are used for creating average values for price data. These can be requested by going to '/now/CURRENCY' without specifying a particular exchange.

### CODE REVIEW

**Comment by ChristopherA** [comment]
I'd like to get at least one +1 review from @Fonta1n3, @gg2001 or @jodobear that this PR builds and works, before merging to master.

**Comment by gg2001** [comment]
I tried installing it using the `install.sh` file as a sudo user on a new Ubuntu 18 VM, however it seems that the script got confused about which directory spotbit is in. These are the main errors I got:

```
cp: cannot stat '/usr/bin/python3.8': No such file or directory
ERROR: Could not open requirements file: [Errno 2] No such file or directory: './requirements.txt'
```

```
creating systemd service...
cp: cannot stat './spotbit.service': No such file or directory
```

```
cat: spotbit_example.config: No such file or directory
```

```
python3: can't open file './configure.py': [Errno 2] No such file or directory
```

Here are the full terminal logs: [Terminal Saved Output.txt](https://github.com/BlockchainCommons/spotbit/files/5222320/Terminal.Saved.Output.txt)


I'll try doing a manual install of spotbit and testing it.

**Comment by watersnake1** [comment]
I've seen that issue before, I would try just running the script a second
time with no changes. For some reason, after downloading the source for the
first time, the script cannot see the files in its working dir. On a second
run it will work.
Christian

**Comment by gg2001** [comment]
Thanks for that, Spotbit started up fine after running `install.sh` again. I tested a couple currency and exchange combinations on the `/now` API call and they worked well. 

I got an issue when making a `/now/<currency>` API call, where I got this output:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

Another issue was that Tor failed to start up, some problem with the user permissions:

```
Sep 16 00:58:28.194 [notice] Read configuration file "/etc/tor/torrc".
Sep 16 00:58:28.196 [warn] /var/lib/tor/Spotbit/ is not owned by this user (root, 0) but by debian-tor (111). Perhaps you are running Tor as the wrong user?
Sep 16 00:58:28.200 [warn] Failed to parse/validate config: Failed to configure rendezvous options. See logs for details.
Sep 16 00:58:28.200 [err] Reading config failed--see warnings above.
```

**Comment by ChristopherA** [comment]
Maybe ask @jodobear to take a look?

**Comment by watersnake1** [comment]
Hi Gautham,

How are you running tor? The tor hidden service directory is owned by the
debian-tor user, so if you try to run tor with something like "sudo tor" it
will not work. If you run "sudo systemctl start tor" it should be run from
the debian tor user for you.

That internal server error was being caused because the install script
wasn't copying the config file over to the right place. I fixed it now and
tested on a debian VM. Still working on the install script not finding
files in the current directory on the first run, so the install script
still needs to be run twice. I've asked jodobear to take a look when he can
as well.

Christian

**Review by ChristopherA — APPROVED** [review]
I am going to merge this, but mostly because a) it is working for gordian now, and b) technically we are still alpha.

We should really find a second regular reviewer of this project that actually will test it in some way, possibly @jodobear as we should add this to the linux Bitcoin-Standup scripts. In general, we should not release code to master without it being reviewed and tested by someone other than the submitter.

My other advice is to separate README and documentation PRs from functional PRs (except where README or doc is specific to the functional change being submitted).

**Pull request merged**
