### PR TITLE
Nick Ochiel Changes

### PR DESCRIPTION
**Pull request by deymow**
Dear Admin,

Kindly receive this pull request as project changes made by Nick

Thanks

### CODE REVIEW

**Comment by shannona** [comment]
Hey, @nochiel is this something we should merge in, or do you already have it taken care of? Thanks!

**Review by nochiel — CHANGES_REQUESTED** [review]
@deymow These changes should not be added as they are outdated. Please reference https://github.com/BlockchainCommons/spotbit/tree/master as your baseline.  Any new functionality should build from that branch.

**Comment by nochiel** [comment]
@deymow Please close this PR.

**Comment by shannona** [comment]
Closing this per @nochiel

**Pull request closed without merging**
